<?php if(function_exists("register_field_group")){
}
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_contact-us',
		'title' => 'Contact Us',
		'fields' => array (
			array (
				'key' => 'field_54d29fd4c4970',
				'label' => 'E-mail',
				'name' => 'contact-email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_54d2a2ba90fa1',
				'label' => 'Office Phone',
				'name' => 'contact-tel-office',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a3935f258',
				'label' => '24hr Hot Line',
				'name' => 'contact-tel-hot-line',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a47681e57',
				'label' => 'Hours Monday',
				'name' => 'contact-hr-monday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a4d8d7b19',
				'label' => 'Hours Tuesday',
				'name' => 'contact-hr-tuesday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a68dd7ba0',
				'label' => 'Hours Wednesday',
				'name' => 'contact-hr-wednesday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a5a08408d',
				'label' => 'Hours Thursday',
				'name' => 'contact-hr-thursday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a794a7d34',
				'label' => 'Hours Friday',
				'name' => 'contact-hr-friday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a799a7d35',
				'label' => 'Hours Sunday',
				'name' => 'contact-hr-sunday',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d2a7f0bba2f',
				'label' => ' Map',
				'name' => 'contact-map',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_options',
		'title' => 'Options',
		'fields' => array (
			array (
				'key' => 'field_54a956a07d319',
				'label' => 'Home',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54a9ce3945281',
				'label' => 'Primeiro Banner',
				'name' => 'home_banner_1',
				'type' => 'image',
				'instructions' => 'Adicione a imagem para o primeiro banner da Home.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_54a9ceb87a0f9',
				'label' => 'Link do Primeiro Banner',
				'name' => 'home_banner_1_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a9ce6045282',
				'label' => 'Vídeo',
				'name' => 'home_video',
				'type' => 'text',
				'instructions' => 'Adicione a URL para o vídeo de destaque da Home.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a956ad7d31a',
				'label' => 'Diferencial',
				'name' => 'home_differential',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_54a958a18e5a7',
				'label' => 'Segundo Banner',
				'name' => 'home_banner_2',
				'type' => 'image',
				'instructions' => 'Adicione a imagem para o segundo banner da Home.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_54a9d06d0495e',
				'label' => 'Link do Segundo Banner',
				'name' => 'home_banner_2_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a95991649d8',
				'label' => 'Terceiro Banner',
				'name' => 'home_banner_3',
				'type' => 'image',
				'instructions' => 'Adicione a imagem para o terceiro banner da Home.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_54a9d091daf83',
				'label' => 'Link do Terceiro Banner',
				'name' => 'home_banner_3_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a9d561fc259',
				'label' => 'Footer',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54a9d5cafc25a',
				'label' => 'Endereço',
				'name' => 'footer_address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a9d634fc25b',
				'label' => 'Telefone',
				'name' => 'footer_phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a9d657fc25c',
				'label' => 'Fax',
				'name' => 'footer_fax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54a9d668fc25d',
				'label' => 'E-mail',
				'name' => 'footer_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
